language: python
python:
  - "3.9"
install:
  - pip install -e . --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run --source=lot setup.py test
notifications:
  email:
    recipients:
      - bcusack78@gmail.com
    on_success: change
    on_failure: change
after_success:
  - coveralls
